# Generated by Django 4.0.7 on 2023-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_sepecial_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_sepecial_yeaer',
            field=models.BooleanField(default=False),
        ),
    ]
