# Generated by Django 4.0.7 on 2023-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_is_sepecial_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='is_sepecial_month',
            new_name='is_special_month',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_sepecial_yeaer',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_status',
            field=models.BooleanField(default=True),
        ),
    ]
